name: time_manager

volumes:
  database:

networks:
  backend:
      driver: bridge
  frontend:
      driver: bridge

services:

  database:
    #container_name: time_manager-database
    image: postgres:latest
    env_file: .env.dev
    volumes: 
      - database:/var/lib/postgresql/data
    networks:
      - backend

  api:
    #container_name: time_manager-api
    #image: phoenix_api
    pull_policy: build 
    # restart: unless-stopped
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file: .env.dev
    depends_on:
      - database
    networks:
      - backend 
      - frontend

  webapp:
    #container_name: time_manager_webapp
    #image: vuejs_webapp
    pull_policy: build
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - api 
    ports:
      - "5173:80"
    networks:
      - frontend

 
