name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: siuuu69
          password: 123!siuuu

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: siuuu69/backend:${{ github.sha }}
          cache-from: type=registry,ref=siuuu69/backend:latest
          cache-to: type=inline

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: siuuu69/frontend:${{ github.sha }}
          cache-from: type=registry,ref=siuuu69/frontend:latest
          cache-to: type=inline
