name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: epitechmscpropromo2026-arc-runners

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: siuuu69
          password: 123!siuuu

      - name: Build and Push Backend
        uses: aevea/action-kaniko@master
        with:
          image: siuuu69/backend
          username: siuuu69
          password: 123!siuuu
          tag: ${{ github.sha }}
          path: ./back

      - name: Build and Push Frontend
        uses: aevea/action-kaniko@master
        with:
          image: siuuu69/frontend
          username: siuuu69
          password: 123!siuuu
          tag: ${{ github.sha }}
          path: ./front
