name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted  # Using self-hosted runner
    defaults:
      run:
        working-directory: ./back
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make gcc libssl-dev automake autoconf
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15.7'    
        otp-version: '26'         
    
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    
    - name: Install dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
    
    - name: Run tests
      run: mix test

  build:
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: siuuu69
        password: 123!siuuu
    
    - name: Build and push Backend
      uses: docker/build-push-action@v2
      with:
        context: ./back
        push: true
        tags: siuuu69/backend:${{ github.sha }}
    
    - name: Build and push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./front
        push: true
        tags: siuuu69/frontend:${{ github.sha }}
