name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: epitechmscpropromo2026-arc-runners

    steps:
      - uses: actions/checkout@v2

      - name: Install Buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - name: Login to DockerHub
        run: |
          echo "123!siuuu" | buildah login -u siuuu69 --password-stdin docker.io

      - name: Build and push Backend
        run: |
          cd back
          buildah bud -t docker.io/siuuu69/backend:${{ github.sha }} .
          buildah push docker.io/siuuu69/backend:${{ github.sha }}

      - name: Build and push Frontend
        run: |
          cd front
          buildah bud -t docker.io/siuuu69/frontend:${{ github.sha }} .
          buildah push docker.io/siuuu69/frontend:${{ github.sha }}
